
export type MuscleGroupOption = {
    label: string;
    value: string;
};

export const MuscleGroupColors = {
    chest: 'green',
    back: 'blue',
    shoulders: 'orange',
    arms: 'purple',
    legs: 'brown',
    core: 'yellow',
    cardio: 'red',
    other: 'gray',
};

export const muscleValueToColor: Record<string, string> = {
    "pectoralis major": MuscleGroupColors.chest,
    "pectoralis minor": MuscleGroupColors.chest,
    "serratus anterior": MuscleGroupColors.chest,
    "subclavius": MuscleGroupColors.shoulders,
    "deltoid-anterior": MuscleGroupColors.shoulders,
    "deltoid-lateral": MuscleGroupColors.shoulders,
    "deltoid-posterior": MuscleGroupColors.shoulders,
    "supraspinatus": MuscleGroupColors.shoulders,
    "infraspinatus": MuscleGroupColors.shoulders,
    "teres minor": MuscleGroupColors.shoulders,
    "subscapularis": MuscleGroupColors.shoulders,
    "teres major": MuscleGroupColors.shoulders,
    "latissimus dorsi": MuscleGroupColors.back,
    "trapezius-upper": MuscleGroupColors.shoulders,
    "trapezius-middle": MuscleGroupColors.shoulders,
    "trapezius-lower": MuscleGroupColors.shoulders,
    "levator scapulae": MuscleGroupColors.shoulders,
    "rhomboid major": MuscleGroupColors.shoulders,
    "rhomboid minor": MuscleGroupColors.shoulders,
    "coracobrachialis": MuscleGroupColors.shoulders,
    "biceps brachii-long": MuscleGroupColors.arms,
    "biceps brachii-short": MuscleGroupColors.arms,
    "brachialis": MuscleGroupColors.arms,
    "triceps brachii-long": MuscleGroupColors.arms,
    "triceps brachii-lateral": MuscleGroupColors.arms,
    "triceps brachii-medial": MuscleGroupColors.arms,
    "anconeus": MuscleGroupColors.arms,
    "pronator teres": MuscleGroupColors.arms,
    "pronator radii": MuscleGroupColors.arms,
    "supinator": MuscleGroupColors.arms,
    "brachioradialis": MuscleGroupColors.arms,
    "extensor carpi radialis longus": MuscleGroupColors.arms,
    "extensor carpi radialis brevis": MuscleGroupColors.arms,
    "extensor carpi ulnaris": MuscleGroupColors.arms,
    "extensor digitorum": MuscleGroupColors.arms,
    "extensor digiti minimi": MuscleGroupColors.arms,
    "flexor carpi radialis": MuscleGroupColors.arms,
    "flexor carpi ulnaris": MuscleGroupColors.arms,
    "flexor digitorum superficialis": MuscleGroupColors.arms,
    "flexor digitorum profundus": MuscleGroupColors.arms,
    "palmaris longus": MuscleGroupColors.arms,
    "rectus abdominis": MuscleGroupColors.core,
    "external oblique": MuscleGroupColors.core,
    "obliquus internus": MuscleGroupColors.core,
    "transversus abdominis": MuscleGroupColors.core,
    "quadratus lumborum": MuscleGroupColors.core,
    "erector spinae": MuscleGroupColors.core,
    "multifidus": MuscleGroupColors.core,
    "rotatores": MuscleGroupColors.core,
    "semispinalis": MuscleGroupColors.core,
    "splenius capitis": MuscleGroupColors.core,
    "splenius cervicis": MuscleGroupColors.core,
    "iliopsoas": MuscleGroupColors.core,
    "tensor fasciae latae": MuscleGroupColors.legs,
    "sartorius": MuscleGroupColors.legs,
    "rectus femoris": MuscleGroupColors.legs,
    "vastus lateralis": MuscleGroupColors.legs,
    "vastus medialis": MuscleGroupColors.legs,
    "vastus intermedius": MuscleGroupColors.legs,
    "gluteus maximus": MuscleGroupColors.legs,
    "gluteus medius": MuscleGroupColors.legs,
    "gluteus minimus": MuscleGroupColors.legs,
    "piriformis": MuscleGroupColors.legs,
    "obturator internus": MuscleGroupColors.legs,
    "gemellus superior": MuscleGroupColors.legs,
    "gemellus inferior": MuscleGroupColors.legs,
    "quadratus femoris": MuscleGroupColors.legs,
    "adductor longus": MuscleGroupColors.legs,
    "adductor brevis": MuscleGroupColors.legs,
    "adductor magnus": MuscleGroupColors.legs,
    "pectineus": MuscleGroupColors.legs,
    "gracilis": MuscleGroupColors.legs,
    "biceps femoris-long": MuscleGroupColors.legs,
    "biceps femoris-short": MuscleGroupColors.legs,
    "semitendinosus": MuscleGroupColors.legs,
    "semimembranosus": MuscleGroupColors.legs,
    "popliteus": MuscleGroupColors.legs,
    "gastrocnemius-medial": MuscleGroupColors.legs,
    "gastrocnemius-lateral": MuscleGroupColors.legs,
    "soleus": MuscleGroupColors.legs,
    "plantaris": MuscleGroupColors.legs,
    "tibialis anterior": MuscleGroupColors.legs,
    "extensor hallucis longus": MuscleGroupColors.legs,
    "extensor digitorum longus": MuscleGroupColors.legs,
    "fibularis longus": MuscleGroupColors.legs,
    "fibularis brevis": MuscleGroupColors.legs,
    "fibularis tertius": MuscleGroupColors.legs,
    "flexor hallucis longus": MuscleGroupColors.legs,
    "flexor digitorum longus": MuscleGroupColors.legs,
    "tibialis posterior": MuscleGroupColors.legs,
    "pelvic floor": MuscleGroupColors.core,
    "cardio": MuscleGroupColors.cardio,
    "hamstrings": MuscleGroupColors.legs,
    "calves": MuscleGroupColors.legs,
    "forearms": MuscleGroupColors.arms,
    "traps": MuscleGroupColors.shoulders,
    "lats": MuscleGroupColors.back,
    "glutes": MuscleGroupColors.legs,
    "quadriceps": MuscleGroupColors.legs,
};

export const muscleGroupOptions: MuscleGroupOption[] = [
    { label: "Pectoralis Major", value: "pectoralis major" },
    { label: "Pectoralis Minor", value: "pectoralis minor" },
    { label: "Serratus Anterior", value: "serratus anterior" },
    { label: "Subclavius", value: "subclavius" },
    { label: "Deltoid (Anterior)", value: "deltoid-anterior" },
    { label: "Deltoid (Lateral)", value: "deltoid-lateral" },
    { label: "Deltoid (Posterior)", value: "deltoid-posterior" },
    { label: "Supraspinatus", value: "supraspinatus" },
    { label: "Infraspinatus", value: "infraspinatus" },
    { label: "Teres Minor", value: "teres minor" },
    { label: "Subscapularis", value: "subscapularis" },
    { label: "Teres Major", value: "teres major" },
    { label: "Latissimus Dorsi", value: "latissimus dorsi" },
    { label: "Trapezius (Upper)", value: "trapezius-upper" },
    { label: "Trapezius (Middle)", value: "trapezius-middle" },
    { label: "Trapezius (Lower)", value: "trapezius-lower" },
    { label: "Levator Scapulae", value: "levator scapulae" },
    { label: "Rhomboid Major", value: "rhomboid major" },
    { label: "Rhomboid Minor", value: "rhomboid minor" },
    { label: "Coracobrachialis", value: "coracobrachialis" },
    { label: "Biceps Brachii (Long Head)", value: "biceps brachii-long" },
    { label: "Biceps Brachii (Short Head)", value: "biceps brachii-short" },
    { label: "Brachialis", value: "brachialis" },
    { label: "Triceps Brachii (Long Head)", value: "triceps brachii-long" },
    { label: "Triceps Brachii (Lateral Head)", value: "triceps brachii-lateral" },
    { label: "Triceps Brachii (Medial Head)", value: "triceps brachii-medial" },
    { label: "Anconeus", value: "anconeus" },
    { label: "Pronator Teres", value: "pronator teres" },
    { label: "Pronator Radii", value: "pronator radii" },
    { label: "Supinator", value: "supinator" },
    { label: "Brachioradialis", value: "brachioradialis" },
    { label: "Extensor Carpi Radialis Longus", value: "extensor carpi radialis longus" },
    { label: "Extensor Carpi Radialis Brevis", value: "extensor carpi radialis brevis" },
    { label: "Extensor Carpi Ulnaris", value: "extensor carpi ulnaris" },
    { label: "Extensor Digitorum", value: "extensor digitorum" },
    { label: "Extensor Digiti Minimi", value: "extensor digiti minimi" },
    { label: "Flexor Carpi Radialis", value: "flexor carpi radialis" },
    { label: "Flexor Carpi Ulnaris", value: "flexor carpi ulnaris" },
    { label: "Flexor Digitorum Superficialis", value: "flexor digitorum superficialis" },
    { label: "Flexor Digitorum Profundus", value: "flexor digitorum profundus" },
    { label: "Palmaris Longus", value: "palmaris longus" },
    { label: "Rectus Abdominis", value: "rectus abdominis" },
    { label: "External Oblique", value: "external oblique" },
    { label: "Obliquus Internus", value: "obliquus internus" },
    { label: "Transversus Abdominis", value: "transversus abdominis" },
    { label: "Quadratus Lumborum", value: "quadratus lumborum" },
    { label: "Erector Spinae", value: "erector spinae" },
    { label: "Multifidus", value: "multifidus" },
    { label: "Rotatores", value: "rotatores" },
    { label: "Semispinalis", value: "semispinalis" },
    { label: "Splenius Capitis", value: "splenius capitis" },
    { label: "Splenius Cervicis", value: "splenius cervicis" },
    { label: "Iliopsoas", value: "iliopsoas" },
    { label: "Tensor Fasciae Latae", value: "tensor fasciae latae" },
    { label: "Sartorius", value: "sartorius" },
    { label: "Rectus Femoris", value: "rectus femoris" },
    { label: "Vastus Lateralis", value: "vastus lateralis" },
    { label: "Vastus Medialis", value: "vastus medialis" },
    { label: "Vastus Intermedius", value: "vastus intermedius" },
    { label: "Gluteus Maximus", value: "gluteus maximus" },
    { label: "Gluteus Medius", value: "gluteus medius" },
    { label: "Gluteus Minimus", value: "gluteus minimus" },
    { label: "Piriformis", value: "piriformis" },
    { label: "Obturator Internus", value: "obturator internus" },
    { label: "Gemellus Superior", value: "gemellus superior" },
    { label: "Gemellus Inferior", value: "gemellus inferior" },
    { label: "Quadratus Femoris", value: "quadratus femoris" },
    { label: "Adductor Longus", value: "adductor longus" },
    { label: "Adductor Brevis", value: "adductor brevis" },
    { label: "Adductor Magnus", value: "adductor magnus" },
    { label: "Pectineus", value: "pectineus" },
    { label: "Gracilis", value: "gracilis" },
    { label: "Biceps Femoris (Long Head)", value: "biceps femoris-long" },
    { label: "Biceps Femoris (Short Head)", value: "biceps femoris-short" },
    { label: "Semitendinosus", value: "semitendinosus" },
    { label: "Semimembranosus", value: "semimembranosus" },
    { label: "Popliteus", value: "popliteus" },
    { label: "Gastrocnemius (Medial Head)", value: "gastrocnemius-medial" },
    { label: "Gastrocnemius (Lateral Head)", value: "gastrocnemius-lateral" },
    { label: "Soleus", value: "soleus" },
    { label: "Plantaris", value: "plantaris" },
    { label: "Tibialis Anterior", value: "tibialis anterior" },
    { label: "Extensor Hallucis Longus", value: "extensor hallucis longus" },
    { label: "Extensor Digitorum Longus", value: "extensor digitorum longus" },
    { label: "Fibularis Longus", value: "fibularis longus" },
    { label: "Fibularis Brevis", value: "fibularis brevis" },
    { label: "Fibularis Tertius", value: "fibularis tertius" },
    { label: "Flexor Hallucis Longus", value: "flexor hallucis longus" },
    { label: "Flexor Digitorum Longus", value: "flexor digitorum longus" },
    { label: "Tibialis Posterior", value: "tibialis posterior" },
    { label: "Pelvic Floor", value: "pelvic floor" },
    { label: "Cardio", value: "cardio" },
    { label: "Hamstrings", value: "hamstrings" },
    { label: "Calves", value: "calves" },
    { label: "Forearms", value: "forearms" },
    { label: "Traps", value: "traps" },
    { label: "Lats", value: "lats" },
    { label: "Glutes", value: "glutes" },
    { label: "Quadriceps", value: "quadriceps" },
]