INSERT INTO AssessmentType (`id`, `name`, `assessmentUnit`, `assessmentGroupId`)
VALUES
    (1, 'Static', NULL, 1),
    (2, 'Push', NULL, 1),
    (3, 'Pull', NULL, 1),
    (4, 'Overhead Squat', NULL, 1),
    (5, 'Single leg squat', NULL, 1),
    (6, 'Weight', 'lbs', 2),
    (7, 'Body Fat Percentage', '%', 2),
    (8, 'Wrist Circumference', 'inches', 2),
    (9, 'Calf Circumference', 'inches', 2),
    (10, 'Bicep Circumference', 'inches', 2),
    (11, 'Chest Circumference', 'inches', 2),
    (12, 'Thigh Circumference', 'inches', 2),
    (13, 'Waist Circumference', 'inches', 2),
    (14, 'Shoulder Circumference', 'inches', 2),
    (15, 'Hip Circumference', 'inches', 2),
    (16, 'Forearm Circumference', 'inches', 2),
    (17, 'Neck Circumference', 'inches', 2),
    (18, 'Deadlift', 'lbs', 3),
    (19, 'Squat', 'lbs', 3),
    (20, 'Bench Press', 'lbs', 3),
    (21, 'Overhead Press', 'lbs', 3),
    (22, 'Pull Ups', 'reps', 3),
    (23, 'Push Ups', 'reps', 3),
    (24, 'Mile time', 'time', 3),
    (25, 'VO2 Max', 'ml/kg/min', 3),
    (26, '1.5 mile walk', 'time', 3),
    (27, '40 yard dash', 'time', 3),
    (28, 'Vertical Jump', 'inches', 3),
    (29, 'Lower Extremity Functional test (LEFT)', 'time', 3),
    (30, 'Long Jump', 'inches', 3),
    (31, 'Pro Shuttle', 'time', 3);