// This file was generated by Prisma
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const dbHost = process.env.DB_HOST;
const dbPort = process.env.DB_PORT;
const dbUser = process.env.DB_USER;
const dbPassword = process.env.DB_PASSWORD;
const dbName = process.env.DB_NAME;

if (!dbHost || !dbPort || !dbUser || !dbPassword || !dbName) {
	throw new Error('Missing required DB env vars. Expected DB_HOST, DB_PORT, DB_USER, DB_PASSWORD, DB_NAME.');
}

const datasourceUrl = `mysql://${encodeURIComponent(dbUser)}:${encodeURIComponent(dbPassword)}@${dbHost}:${dbPort}/${dbName}`;

export default defineConfig({
	schema: 'prisma/schema.prisma',
	migrations: {
		path: 'prisma/migrations',
	},
	datasource: {
		url: datasourceUrl,
	},
});
