export const Routes = {
    Assessment: "/assessment",
    AssessmentGroup: "/assessment/group",
    AssessmentLog: "/assessment/log",
    AuthLogin: "/auth/login",
    AuthSignup: "/auth/signup",
    Clients: "/clients",
    ClientContact: "/clientcontact",
    ClientPlan: "/plan/client",
    Contacts: "/contact",
    Exercise: "/exercises",
    ExerciseCreate: "/exercises/create",
    Health: "/health",
    Plan: "/plan",
    TargetMetricTypes: "/models/target-metrics",
    WorkoutRoutineStages: "/models/workout-routine-stages",
}
