export const Routes = {
	Assessment: '/assessment',
	AssessmentGroup: '/assessment/group',
	AssessmentLog: '/assessment/log',
	AuthLogin: '/auth/login',
	AuthSignup: '/auth/signup',
	AuthRefresh: '/auth/refresh',
	AuthLogout: '/auth/logout',
	Clients: '/clients',
	ClientContact: '/clientcontact',
	ClientPlan: '/plan/client',
	Contacts: '/contact',
	Exercise: '/exercises',
	Health: '/health',
	Macrocycle: '/cycle/macro',
	Mesocycle: '/cycle/meso',
	Microcycle: '/cycle/micro',
	WorkoutRoutine: '/workout-routine',
	DietPlan: '/diet/plan',
	DietLog: '/diet/log',
};
