export const Routes = {
    Assessment: "/assessment",
    AssessmentGroup: "/assessment/group",
    AssessmentLog: "/assessment/log",
    AuthLogin: "/auth/login",
    AuthSignup: "/auth/signup",
    Clients: "/clients",
    ClientContact: "/clientcontact",
    ClientPlan: "/plan/client",
    Contacts: "/contact",
    Exercise: "/exercises",
    Health: "/health",
    Macrocycle: "/cycle/macro",
    Mesocycle: "/cycle/meso",
    Microcycle: "/cycle/micro",
    Plan: "/plan",
    TargetMetricTypes: "/models/target-metrics",
    WorkoutRoutineStages: "/models/workout-routine-stages",
}
