import { Prisma } from '@libre-train/db/client';
import type {
	AssessmentClientLog,
	Client,
	ClientGoal,
	ClientGoalAssessment,
	Contact,
	CycleLevel,
	DietPlan,
	GoalStatus,
	Macrocycle,
	Mesocycle,
	Microcycle,
} from './models';

export type OmitAutogeneratedFields<T> = Omit<T, 'id' | 'created_at' | 'updated_at'>;

export type ResponseWithError<T> = T | { hasError: true; errorMessage: string };

export type GoalAssessmentInput = {
	assessment_type_id: number;
	target_value: string;
};

export type CreateClientGoalRequest = {
	client_id: number;
	macrocycle_id?: number;
	mesocycle_id?: number;
	microcycle_id?: number;
	description?: string;
	target_date?: string;
	assessments: GoalAssessmentInput[];
};

export type UpdateClientGoalRequest = {
	macrocycle_id?: number;
	mesocycle_id?: number;
	microcycle_id?: number;
	description?: string;
	target_date?: string;
	status?: GoalStatus;
	assessments?: GoalAssessmentInput[];
};

export type ClientGoalSearchParams = {
	clientId?: string;
	trainerId?: string;
	status?: GoalStatus;
	cycleLevel?: CycleLevel;
	cycleId?: string;
	activeCyclesOnly?: string;
};

export type GoalClientSummary = { id: number; first_name: string; last_name: string };

export type ClientGoalAssessmentWithType = ClientGoalAssessment & {
	AssessmentType: { id: number; name: string; assessmentUnit?: string };
};

export type ClientGoalWithRelations = ClientGoal & {
	assessments: ClientGoalAssessmentWithType[];
	Macrocycle?: Pick<Macrocycle, 'id' | 'cycle_name' | 'cycle_start_date' | 'cycle_end_date' | 'is_active'>;
	Mesocycle?: Pick<Mesocycle, 'id' | 'cycle_name' | 'cycle_start_date' | 'cycle_end_date' | 'is_active'>;
	Microcycle?: Pick<Microcycle, 'id' | 'cycle_name' | 'cycle_start_date' | 'cycle_end_date' | 'is_active'>;
	Client?: GoalClientSummary;
};

export type AddClientFormValues = {
	firstName?: string;
	lastName?: string;
	phoneNumber?: string;
	email?: string;
	height?: number;
	dob?: string;
	img64?: string;
	notes?: string;
	trainerId: number;
	/** When set, link the new client to this existing contact and update its fields rather than creating a new contact. */
	contactId?: number;
};

export type DailyUpdateData = {
	weight?: number;
	body_fat?: number;
	calories?: number;
	target_calories?: number;
	protein?: number;
	target_protein?: number;
	carbs?: number;
	target_carbs?: number;
	fats?: number;
	target_fats?: number;
};

export type DailyUpdateRequest = {
	clientId: number;
	date: string; // ISO string
	data: DailyUpdateData;
};

export type DashboardData = {
	clientId: number;
	first_name: string;
	last_name: string;
	email: string;
	phone: string;
	height?: number;
	img?: string;
	logged_weight: number;
	logged_calories?: number;
	logged_body_fat?: number;
	logged_protein?: number;
	logged_carbs?: number;
	logged_fats?: number;
	target_calories?: number;
	target_protein?: number;
	target_carbs?: number;
	target_fats?: number;
};

export type ErrorResponse = {
	message: string;
};

export type DashboardResponse = DashboardData | ErrorResponse;

export type DashboardSummaryQuery = {
	clientId: string;
	startDate: string;
	endDate: string;
};

export type DashboardWeeklySummary = {
	avg_weight: number;
	avg_bodyfat: number;
	avg_calories: number;
	total_macros: number;
	target_macros: number;
};

export type DashboardWeeklySummaryResponse = DashboardWeeklySummary[] | ErrorResponse;

export type AssessmentClientLogCreateRequest = {
	clientId: number;
	assessments: Omit<AssessmentClientLog, 'id' | 'clientId'>[];
};

export type AssessmentClientLogSearchOptions = {
	group?: string;
	type?: string;
	start?: string;
	end?: string;
	page?: number;
	pageSize?: number;
};

export type MacrocycleSearchParams = {
	active?: string;
	date?: string;
};

export type MesocycleUpdateRequest = Partial<Omit<Mesocycle, 'id' | 'client_id' | 'macrocycle_id'>>;

export type MesocycleSearchParams = {
	active?: string;
	macrocycleId?: string;
	date?: string;
};

export type MicrocycleUpdateRequest = Partial<Omit<Microcycle, 'id' | 'client_id' | 'mesocycle_id'>>;

export type MicrocycleUpdateRoutinesRequest = {
	routines: CreateWorkoutRoutine[];
};

export type MicrocycleSearchParams = {
	active?: string;
	mesocycleId?: string;
	clientId?: string;
	date?: string;
};

export enum TrainingCycleType {
	Macrocycle = 1,
	Mesocycle = 2,
	Microcycle = 3,
}

export type UpdateWorkoutRoutineRequest = Omit<CreateWorkoutRoutine, 'id' | 'microcycle_id' | 'routine_index' | 'isActive'>;

export type GetDietPlanSearchParams = {
	clientId?: string;
	trainerId?: string;
	isActive?: string;
};

export type GetDietPlanLogEntrySearchParams = {
	clientId?: string;
	dietPlanId?: string;
	logDate?: string;
	startDate?: string;
	endDate?: string;
};

export type UpdateClientRequest = OmitAutogeneratedFields<Partial<Client>>;

export type UpdateContactRequest = OmitAutogeneratedFields<Partial<Contact>>;

export type CreateContactRequest = OmitAutogeneratedFields<Contact>;

export type ContactWithFlags = Contact & {
	isTrainer: boolean;
	hasClient: boolean;
};

export type CreateWorkoutRoutine = Omit<OmitAutogeneratedFields<Prisma.WorkoutRoutineUncheckedCreateInput>, 'exercise_groups'> & {
	exercise_groups: Array<
		Omit<OmitAutogeneratedFields<Prisma.PlannedExerciseGroupUncheckedCreateInput>, 'exercises'> & {
			exercises: Array<OmitAutogeneratedFields<Prisma.PlannedExerciseUncheckedCreateInput>>;
		}
	>;
};

export type CreateDietPlan = Omit<OmitAutogeneratedFields<DietPlan>, 'id' | 'isActive'>;
