CREATE TABLE Mesocycle (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    client_id INT UNSIGNED NOT NULL,
    cycle_name VARCHAR(255) DEFAULT NULL,
    macrocycle_id INT UNSIGNED NOT NULL,
    cycle_start_date DATE NOT NULL,
    cycle_end_date DATE NOT NULL,
    opt_levels VARCHAR(255) DEFAULT NULL,
    cardio_levels VARCHAR(255) DEFAULT NULL,
    notes VARCHAR(512) DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE CASCADE,
    FOREIGN KEY (macrocycle_id) REFERENCES Macrocycle(id) ON DELETE CASCADE
)