CREATE TABLE Microcycle (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    mesocycle_id INT UNSIGNED NOT NULL,
    client_id INT UNSIGNED NOT NULL,
    cycle_name VARCHAR(255) DEFAULT NULL,
    cycle_start_date DATE NOT NULL,
    cycle_end_date DATE NOT NULL,
    notes VARCHAR(512) DEFAULT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (mesocycle_id) REFERENCES Mesocycle(id) ON DELETE CASCADE,
    FOREIGN KEY (client_id) REFERENCES Client(id) ON DELETE CASCADE
)