name: Deploy

on:
  push:
    branches:
      - main
      - release

jobs: 
  deploy:
    runs-on: self-hosted
    environment: Test
    
    steps:
      - uses: actions/checkout@v4

      - name: Bun setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Create Client env
        run: |
          cat > client/.env << EOF
          VITE_API_URL=${{ vars.API_URL }}
          VITE_BASE_URL=/${{ vars.FRONTEND_APP_NAME }}
          VITE_ENVIRONMENT=${{ vars.ENVIRONMENT }}
          EOF

      - name: Build Client
        run: bun run build --filter @libre-train/client

      - name: Build Server container
        run: |
          cat > server/.env << EOF
          NODE_ENV=${{ vars.ENVIRONMENT }}
          DB_HOST=${{ vars.DB_HOST }}
          DB_PORT=${{ vars.DB_PORT }}
          DB_USER=${{ vars.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ vars.DB_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}
          FRONTEND_URL=https://${{ vars.FRONTEND_DOMAIN }}/${{ vars.FRONTEND_APP_NAME }}
          EOF

          docker compose down --remove-orphans
          docker compose up --build -d --remove-orphans

          docker compose ps

      - name: Deploy Frontend app
        run: |
          echo "Deploying frontend app to /var/www/${{ vars.FRONTEND_DOMAIN }}/html/${{ vars.FRONTEND_APP_NAME }}"
          sudo mkdir -p /var/www/${{ vars.FRONTEND_DOMAIN }}/html/${{ vars.FRONTEND_APP_NAME }}
          sudo chown -R www-data:www-data /var/www/${{ vars.FRONTEND_DOMAIN }}/html/${{ vars.FRONTEND_APP_NAME }}
          sudo chmod -R 755 /var/www/${{ vars.FRONTEND_DOMAIN }}/html/${{ vars.FRONTEND_APP_NAME }}
          sudo rsync -av --delete client/dist/ /var/www/${{ vars.FRONTEND_DOMAIN }}/html/${{ vars.FRONTEND_APP_NAME }}/